""""
String constants used as keyword argument names throughout the module
"""
GRIP_LENGTH = 'grip_length'
GRIP_WIDTH = 'grip_width'
TAPER_LENGTH = 'taper_length'
REDUCED_LENGTH = 'reduced_length'
REDUCED_WIDTH = 'reduced_width'
PART_NAME = 'part_name'
SKETCH_NAME = 'sketch_name'
MODEL_NAME = 'model_name'
SECTION_NAME = 'section_name'
SOURCE_MATERIAL_NAME = 'source_material_name'
TARGET_MATERIAL_NAME = 'target_material_name'
MATERIAL_TEMPLATE = 'material_template'
FULL_VOLUME_SET = 'full_volume_set'
FRICTION_COEFFICIENT = 'friction_coefficient'
FIXED_SET = 'fixed_set'
MOVABLE_SET = 'movable_set'
DISPLACEMENT_DURATION = 'displacement_duration'
JOB_NAME = 'job_name'
RUN_JOB_AUTOMATICALLY = 'run_job_automatically'
SPECIMEN_TEMPERATURE = 'initial_temperature'
SPECIMEN_LENGTH = 'specimen_length'
SPECIMEN_BASE_AREA = 'specimen_base_area'
SPECIMEN_BASE_RADIUS = 'specimen_base_radius'
SPECIMEN_VELOCITY = 'specimen_velocity'
TOOL_RADIUS = 'tool_radius'
TOOL_DISPLACEMENT = 'tool_displacement'
MESH_EDGE_LENGTH = 'mesh_edge_length'
ASSEMBLY_NAME = 'assembly_name'
STEP_NAME = 'step_name'
ENCASTRE_BC = 'fixed_bc'
DISPLACEMENT_BC = 'displacement_bc'
TEMPERATURE_FIELD_NAME = 'temperature_field_name'
CPU_COUNT = 'cpu_count'
USER_SUBROUTINE = 'user_subroutine'

INITIAL_STEP = 'Initial'
