""""
String constants used as keyword argument names throughout the module
"""
GRIP_LENGTH = 'grip_length'
GRIP_WIDTH = 'grip_width'
TAPER_LENGTH = 'taper_length'
REDUCED_LENGTH = 'reduced_length'
REDUCED_WIDTH = 'reduced_width'
PART_NAME = 'part_name'
SKETCH_NAME = 'sketch_name'
MODEL_NAME = 'model_name'
SECTION_NAME = 'section_name'
MATERIAL_NAME = 'material_name'
MATERIAL_TEMPLATE = 'material_template'
FULL_VOLUME_SET = 'full_volume_set'
FIXED_GRIP_SET = 'fixed_grip_set'
MOVABLE_GRIP_SET = 'movable_grip_set'
GRIP_DISPLACEMENT = 'grip_displacement'
DISPLACEMENT_DURATION = 'displacement_duration'
JOB_NAME = 'job_name'
RUN_JOB_AUTOMATICALLY = 'run_job_automatically'
SPECIMEN_TEMPERATURE = 'initial_temperature'
MESH_EDGE_LENGTH = 'mesh_edge_length'
ASSEMBLY_NAME = 'assembly_name'
STEP_NAME = 'step_name'
ENCASTRE_BC = 'fixed_bc'
DISPLACEMENT_BC = 'displacement_bc'
TEMPERATURE_FIELD_NAME = 'temperature_field_name'
CPU_COUNT = 'cpu_count'
USER_SUBROUTINE = 'user_subroutine'

INITIAL_STEP = 'Initial'
